# Generated by Django 5.2.4 on 2025-07-14 21:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bebida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="bebidas/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ingredientes", models.TextField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="pizzas/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sobrenome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("endereco_entrega", models.CharField(max_length=200)),
                ("numero", models.CharField(max_length=11)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preco_final", models.DecimalField(decimal_places=2, max_digits=6)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="capizzas_restaurant.cliente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompraBebida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "bebida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="capizzas_restaurant.bebida",
                    ),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="capizzas_restaurant.compra",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="compra",
            name="bebidas",
            field=models.ManyToManyField(
                blank=True,
                through="capizzas_restaurant.CompraBebida",
                to="capizzas_restaurant.bebida",
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="pizza_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pizza_sabor1",
                to="capizzas_restaurant.pizza",
            ),
        ),
        migrations.AddField(
            model_name="compra",
            name="pizza_2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pizza_sabor2",
                to="capizzas_restaurant.pizza",
            ),
        ),
        migrations.CreateModel(
            name="Promocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="promocoes/"),
                ),
                ("ativa", models.BooleanField(default=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "bebidas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="promocoes",
                        to="capizzas_restaurant.bebida",
                    ),
                ),
                (
                    "pizzas",
                    models.ManyToManyField(
                        related_name="promocoes", to="capizzas_restaurant.pizza"
                    ),
                ),
            ],
        ),
    ]
