# Generated by Django 5.2.4 on 2025-07-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capizzas_restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="endereco_entrega",
            field=models.CharField(default="Endereço Padrão", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="numero",
            field=models.CharField(default="0", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="sobrenome",
            field=models.CharField(default="Cesar", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(
                default="otaciliocesarsantos@gmail.com", max_length=254
            ),
            preserve_default=False,
        ),
    ]
