# Generated by Django 5.2.4 on 2025-07-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capizzas_restaurant", "0002_produtodiverso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="numero",
            field=models.CharField(max_length=15),
        ),
    ]
