# Generated by Django 5.2.4 on 2025-07-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "capizzas_restaurant",
            "0002_cliente_endereco_entrega_cliente_numero_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="senha",
            field=models.CharField(default="1234", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cliente",
            name="numero",
            field=models.CharField(max_length=11),
        ),
    ]
