# Generated by Django 5.2.4 on 2025-07-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capizzas_restaurant", "0003_cliente_senha_alter_cliente_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
