# Generated by Django 5.2.4 on 2025-07-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capizzas_restaurant", "0003_alter_cliente_numero"),
    ]

    operations = [
        migrations.CreateModel(
            name="Borda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sabor", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
