# Generated by Django 5.2.4 on 2025-07-10 20:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capizzas_restaurant", "0004_alter_cliente_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pedido",
            name="cliente",
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("preco_final", models.DecimalField(decimal_places=2, max_digits=6)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="capizzas_restaurant.cliente",
                    ),
                ),
                (
                    "pizza_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pizza_sabor1",
                        to="capizzas_restaurant.pizza",
                    ),
                ),
                (
                    "pizza_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pizza_sabor2",
                        to="capizzas_restaurant.pizza",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ItemPedido",
        ),
        migrations.DeleteModel(
            name="Pedido",
        ),
    ]
