# Generated by Django 5.2.4 on 2025-07-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("capizzas_restaurant", "0004_borda"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Borda",
        ),
    ]
