# Generated by Django 5.2.4 on 2025-07-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capizzas_restaurant", "0006_borda"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="borda",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
