# Generated by Django 5.2.4 on 2025-07-11 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capizzas_restaurant", "0006_remove_cliente_senha_cliente_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bebida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="bebidas/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompraBebida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "bebida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="capizzas_restaurant.bebida",
                    ),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="capizzas_restaurant.compra",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="compra",
            name="bebidas",
            field=models.ManyToManyField(
                blank=True,
                through="capizzas_restaurant.CompraBebida",
                to="capizzas_restaurant.bebida",
            ),
        ),
    ]
