# Generated by Django 5.2.4 on 2025-07-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capizzas_restaurant", "0007_bebida_comprabebida_compra_bebidas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("imagem", models.ImageField(upload_to="promocoes/")),
                ("ativa", models.BooleanField(default=True)),
                (
                    "pizzas",
                    models.ManyToManyField(
                        related_name="promocoes", to="capizzas_restaurant.pizza"
                    ),
                ),
            ],
        ),
    ]
