# Generated by Django 5.2.4 on 2025-08-01 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capizzas_restaurant", "0007_compra_borda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="pizza_1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pizza_sabor1",
                to="capizzas_restaurant.pizza",
            ),
        ),
    ]
