# Generated by Django 5.2.4 on 2025-08-01 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capizzas_restaurant", "0008_alter_compra_pizza_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compra",
            name="pizza_1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pizza_sabor1",
                to="capizzas_restaurant.pizza",
            ),
        ),
    ]
