# Generated by Django 5.2.4 on 2025-07-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capizzas_restaurant", "0008_promocao"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocao",
            name="bebidas",
            field=models.ManyToManyField(
                blank=True, related_name="promocoes", to="capizzas_restaurant.bebida"
            ),
        ),
    ]
