# Generated by Django 5.2.4 on 2025-08-01 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capizzas_restaurant", "0009_alter_compra_pizza_1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compra",
            name="borda",
        ),
        migrations.RemoveField(
            model_name="compra",
            name="pizza_1",
        ),
        migrations.RemoveField(
            model_name="compra",
            name="pizza_2",
        ),
        migrations.RemoveField(
            model_name="compra",
            name="quantidade",
        ),
        migrations.CreateModel(
            name="CompraItemPizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("borda", models.JSONField(blank=True, null=True)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=6)),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_pizza",
                        to="capizzas_restaurant.compra",
                    ),
                ),
                (
                    "pizza_1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_pizza_sabor1",
                        to="capizzas_restaurant.pizza",
                    ),
                ),
                (
                    "pizza_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_pizza_sabor2",
                        to="capizzas_restaurant.pizza",
                    ),
                ),
            ],
        ),
    ]
