# Generated by Django 5.2.4 on 2025-08-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "capizzas_restaurant",
            "0010_remove_compra_borda_remove_compra_pizza_1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="codigo_pagamento",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="compra",
            name="status_pagamento",
            field=models.CharField(default="Aguardando", max_length=30),
        ),
    ]
